export const langs = {
  en: {
    greeting: "Hi",
    hourly: "Hourly Forecast",
    daily: "Daily Forecast",
    hour: "Hour",
    day: "Day",
    uvi: "UV",
    sunrise: "Sun rise",
    rise: "Rise",
    sunset: "Sun set",
    set: "Set",
    wind: "Wind",
    rain: "Rain",
    feelsLike: "Feels like",
    humidity: "Humidity",
    dewPoint: "Dew point is",
    cloud: "Cloud",
    lastHour: "in the last hour",
    temp: "Temp",
    day0: "Sunday",
    day1: "Monday",
    day2: "Tueday",
    day3: "Wednesday",
    day4: "Thursday",
    day5: "Friday",
    day6: "Saturday",
    followedCities: "Following Cities",
    setDefault: "Set default",
    unFollow: "Unfollow",
    default: "Default",
    weather: "Weather",
    enterCity: "Enter city",
    forecast: "Forecast",
    details: "Details",
    follow: "Follow",
    back: "Back",
    setting: "Setting",
    lang: "Language",
    degreeUnit: "Degree unit",
    save: "Save",
    cancel: "Cancel",
    nextHour: "in the next 1 hour",
    good: "Good",
    medium: "Medium",
    least: "Least",
    bad: "Bad",
    damnable: "Damnable",
    dangerous: "Dangerous",
  },
  vi: {
    greeting: "Chào",
    hourly: "Dự báo theo giờ",
    daily: "Dự báo theo ngày",
    hour: "Giờ",
    day: "Ngày",
    uvi: "Tia UV",
    sunrise: "Mặt trời mọc",
    sunset: "Mặt trời lặn",
    rise: "Mọc",
    set: "Lặn",
    wind: "Gió",
    rain: "Lượng mưa",
    feelsLike: "Cảm giác như",
    humidity: "Độ ẩm",
    dewPoint: "Điểm sương là",
    cloud: "Mây",
    lastHour: "vào giờ trước",
    temp: "Nhiệt độ",
    day0: "Chủ nhật",
    day1: "Thứ 2",
    day2: "Thứ 3",
    day3: "Thứ 4",
    day4: "Thứ 5",
    day5: "Thứ 6",
    day6: "Thứ 7",
    followedCities: "Các thành phố theo dõi",
    setDefault: "Đặt làm mặc định",
    unFollow: "Bỏ theo dõi",
    default: "Mặc định",
    weather: "Thời tiết",
    enterCity: "Nhập thành phố",
    forecast: "Dự báo",
    details: "Chi tiết",
    follow: "Theo dõi",
    back: "Trở về",
    setting: "Cài đặt",
    lang: "Ngôn ngữ",
    degreeUnit: "Đơn vị đo độ",
    save: "Lưu",
    cancel: "Bỏ qua",
    nextHour: "trong 1 giờ tiếp theo",
    good: "Tốt",
    medium: "Trung bình",
    least: "Kém",
    bad: "Xấu",
    damnable: "Rất xấu",
    dangerous: "Nguy hại",
  },
};

export const colors = {
  0: {
    gradient: ["#3A3A6A", "#25244C"],
    color: "rgba(72, 49, 157, 0.5)",
  },
  1: {
    gradient: ["#2F50A6", "#312AC3"],
    color: "rgba(53, 109, 255, 0.5)",
  },
};

export const aqi = {
  good: {
    color: "#00E600",
    maxIndex: 50,
    quality: "good",
  },
  medium: {
    color: "#FFFA00",
    maxIndex: 100,
    quality: "medium",
  },
  least: {
    color: "#FF7D00",
    maxIndex: 150,
    quality: "least",
  },
  bad: {
    color: "#FF2500",
    maxIndex: 200,
    quality: "bad",
  },
  damnable: {
    color: "#9B174C",
    maxIndex: 300,
    quality: "damnable",
  },
  dangerous: {
    color: "#800E1F",
    maxIndex: 500,
    quality: "dangerous",
  },
};

export const cities = require("./tinh_tp.json");
