export const langs = {
  en: {
    greeting: "Hi",
    hourly: "Hourly Forecast",
    daily: "Daily Forecast",
    hour: "Hour",
    day: "Day",
    uvi: "UV",
    sunrise: "Sun rise",
    rise: "Rise",
    sunset: "Sun set",
    set: "Set",
    wind: "Wind",
    rain: "Rain",
    feelsLike: "Feels like",
    humidity: "Humidity",
    dewPoint: "Dew point is",
    cloud: "Cloud",
    lastHour: "in the last hour",
    temp: "Temp",
    day0: "Sunday",
    day1: "Monday",
    day2: "Tueday",
    day3: "Wednesday",
    day4: "Thursday",
    day5: "Friday",
    day6: "Saturday",
    followedCities: "Following Cities",
    setDefault: "Set default",
    unFollow: "Unfollow",
    default: "Default",
    weather: "Weather",
    enterCity: "Enter city",
    forecast: "Forecast",
    details: "Details",
    follow: "Follow",
    back: "Back",
    setting: "Setting",
    lang: "Language",
    degreeUnit: "Degree unit",
    save: "Save",
    cancel: "Cancel",
    nextHour: "in the next 1 hour",
  },
  vi: {
    greeting: "Chào",
    hourly: "Dự báo theo giờ",
    daily: "Dự báo theo ngày",
    hour: "Giờ",
    day: "Ngày",
    uvi: "Tia UV",
    sunrise: "Mặt trời mọc",
    sunset: "Mặt trời lặn",
    rise: "Mọc",
    set: "Lặn",
    wind: "Gió",
    rain: "Lượng mưa",
    feelsLike: "Cảm giác như",
    humidity: "Độ ẩm",
    dewPoint: "Điểm sương là",
    cloud: "Mây",
    lastHour: "vào giờ trước",
    temp: "Nhiệt độ",
    day0: "Chủ nhật",
    day1: "Thứ 2",
    day2: "Thứ 3",
    day3: "Thứ 4",
    day4: "Thứ 5",
    day5: "Thứ 6",
    day6: "Thứ 7",
    followedCities: "Các thành phố theo dõi",
    setDefault: "Đặt làm mặc định",
    unFollow: "Bỏ theo dõi",
    default: "Mặc định",
    weather: "Thời tiết",
    enterCity: "Nhập thành phố",
    forecast: "Dự báo",
    details: "Chi tiết",
    follow: "Theo dõi",
    back: "Trở về",
    setting: "Cài đặt",
    lang: "Ngôn ngữ",
    degreeUnit: "Đơn vị đo độ",
    save: "Lưu",
    cancel: "Bỏ qua",
    nextHour: "trong 1 giờ tiếp theo",
  },
};
